### PR TITLE
Add OAuth 2.0 credentials generated by the Google Identity Platform.

### PR DESCRIPTION
**Pull request by meitar**

### CODE REVIEW

**Comment by Plazmaz** [comment]
If you revise it to "extension:json googleusercontent client_secret NOT xxxxxxxxxxxx", it will return less false positives.

**Comment by meitar** [comment]
Sure. Are you asking me to update this PR in that way?

**Comment by Plazmaz** [comment]
Nah, just noting it. You can update your PR or keep it, I'm sure @techgaun won't mind either way 😉

**Comment by techgaun** [comment]
Thanks @meitar and @Plazmaz .. its just better to have better dorks with low false positives.. if the fix suggested by @Plazmaz reduces false positives, it would be good to have it updated.

**Comment by Plazmaz** [comment]
@techgaun with my private project, I implemented some basic heuristics to avoid false positives by searching for "negative patterns" such as "xxxxxx". Unfortunately it would take a lot of refactoring to allow this system to work using this technique. However, it might be worth looking at some other dorks and adding tidbits to reduce false positives.

**Comment by techgaun** [comment]
@Plazmaz yup I agree. I need to gather some time to revamp this project but I am lacking of time these days.

If anyone wants to step in to lead the development I am more than happy to share this repo

**Comment by Plazmaz** [comment]
@techgaun unfortunately I'm also short on time. Perhaps you could put something in the readme asking for contributors.

**Comment by meitar** [comment]
> If you revise it to "extension:json googleusercontent client_secret NOT xxxxxxxxxxxx", it will return less false positives.

Do you know how to use GitHub's advanced search operators to do this? The above search modification, that is, just adding [` NOT xxxxxxxxxxxx`] to the existing query, does not reduce the search result set when I try it. I have also looked at [GitHub's Advanced Code Search page](https://github.com/search/advanced) but cannot find an option listed there for *excluding* specific strings from code search results.

Thanks in advance for your advice.

**Comment by Plazmaz** [comment]
Yes it does. https://i.imgur.com/sujpoER.png
It's not many results that it excludes though.

**Comment by meitar** [comment]
> Yes it does. https://i.imgur.com/sujpoER.png

Where are you seeing that? Again, I reiterate that this does not appear on the Github Advanced Code Search page (here's [an archive.is snapshot](https://archive.is/aKHR4)).

**Comment by Plazmaz** [comment]
Under the cheat sheet

**Comment by meitar** [comment]
> Under the cheat sheet

What is "the cheat sheet"? Is it too much to ask of you to just paste a link?

**Comment by Plazmaz** [comment]
There's no link that I can find, just on the search page

**Comment by meitar** [comment]
Ah, I found it. The "link" is:

1. On [the GitHub *regular* Search page](https://github.com/search),
1. Click rhe link that says "prefixes" and what you're calling "the cheat sheet" appears.

**Comment by meitar** [comment]
Okay, running thevsearch again with ` NOT xxxxxxx` appended today takes me from 7,490 results without this clause to 7,487 with it. It removes three results. @techgaun Is that still worth adding to the pull request?

**Comment by techgaun** [comment]
sounds good. thanks for checking that. merging as-is

**Pull request merged**
